presentation.pdf: presentation.tex
	pdflatex presentation.tex
	pdflatex presentation.tex

clean:
	rm presentation.aux \
	   presentation.log \
           presentation.pdf \
	   presentation.toc \
           presentation.out \
           presentation.snm \
           presentation.vrb \
           presentation.nav
